services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ujuz
      POSTGRES_PASSWORD: ujuz
      POSTGRES_DB: ujuz
    ports:
      - "5432:5432"
    volumes:
      - ujuz_pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  ujuz_pg:
